#!/usr/bin/python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import sys
import argparse
sys.path.append('/usr/lib/fpemud-vmake')
from fvm_param import FvmParam
from main_impl import MainImpl


def parseArgs():
    parser = argparse.ArgumentParser()
    parser.add_argument("--title", default="", help="Virtual machine title")
    parser.add_argument("--description", default="", help="Virtual machine description")
    parser.add_argument("--os", help="Virtual machine operating system")
    parser.add_argument("--type", help="Virtual machine type")
    parser.add_argument("path", default="", help="Virtual machine path")
    return parser.parse_args()


if __name__ == "__main__":
    ret = MainImpl(FvmParam(), parseArgs()).main()
    sys.exit(ret)

